// <auto-generated />
using CoreCFirstWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCFirstWebApi.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20210322091942_PlayerMig")]
    partial class PlayerMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreCFirstWebApi.Models.Player", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PTeam")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("PId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
